apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: calculator
  name: queueworker
spec:
  replicas: 10
  selector:
    matchLabels:
      app: queueworker
  template:
    metadata:
      labels:
        app: queueworker
    spec:
      containers:
      - name: queueworker
        image: queueworker
        volumeMounts:
        - name: secrets
          mountPath: "/mnt/secrets"
          readOnly: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
      volumes:
      - name: secrets
        secret:
          secretName: calculator-container-secrets
          optional: false
# ---
# apiVersion: keda.sh/v1alpha1
# kind: TriggerAuthentication
# metadata:
#   namespace: calculator
#   name: azure-servicebus-auth
# spec:
#   podIdentity:
#     provider: azure | azure-workload
#     identity: <identity-name> # identity name
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: calculator
spec:
  scaleTargetRef:
    name: azure-servicebus-queue-function
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: workerqueue
      namespace: crgar-aks-batchsb
      messageCount: "5" # default 5
    authenticationRef:
        name: azure-servicebus-auth # authenticationRef would need either podIdentity or define a connection parameter