apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: calculator
  name: queueworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queueworker
  template:
    metadata:
      labels:
        app: queueworker
    spec:
      containers:
      - name: queueworker
        image: queueworker
        volumeMounts:
        - name: secrets
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: calculator-container-secrets
          optional: false
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  namespace: calculator
  name: azure-servicebus-auth
spec:
  podIdentity:
    provider: azure | azure-workload
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azure-servicebus-queue-scaledobject
  namespace: calculator
spec:
  scaleTargetRef:
    name: azure-servicebus-queue-function
  triggers:
  - type: azure-servicebus
    metadata:
      # Required: queueName OR topicName and subscriptionName
      queueName: workerqueue
      # or
      topicName: functions-sbtopic
      subscriptionName: sbtopic-sub1
      # Required: Define what Azure Service Bus to authenticate to with Managed Identity
      namespace: service-bus-namespace
      # Optional
      messageCount: "5" # default 5
      cloud: AzureGermanCloud # Optional. Default: AzurePublicCloud
    authenticationRef:
        name: azure-servicebus-auth # authenticationRef would need either podIdentity or define a connection parameter