apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      namespace: calculator
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets
          mountPath: "/mnt/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: calculator-container-secrets
          optional: false
---
apiVersion: v1
kind: Service
metadata:
  namespace: calculator
  name: client-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: client